feature-task1 ready
Margarita-Mashkova/warehouse_mediasoft pull request #2
Opened 2024-04-22 09:16 UTC by Margarita-Mashkova

2024-04-24 16:58 UTC, GUR-ok commented
Давай назовем мр "Task1: add price increase scheduling" а не "feature-task1 ready". именно с таким комментарием в итоге смержится сквошнутый коммит в девелоп

2024-04-24 17:09 UTC, GUR-ok requested changes

2024-04-24 17:09 UTC, GUR-ok commented on src/main/java/com/warehouse/aspect/ExecutionTimeAspect.java
> +            System.out.println("Execution time for method " + className + "." + methodName + "() = " + executionTime + " ms");
sout не используем в боевом закоммиченном коде. используем логирование.

2024-04-24 17:09 UTC, GUR-ok commented on src/main/java/com/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +            Class.forName(driverClassName);
Зачем тут Class.forName()?

2024-04-24 17:09 UTC, GUR-ok commented on src/main/java/com/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +            String querySelectProducts = "SELECT id, price FROM product";
все sql квери в константы

2024-04-24 17:09 UTC, GUR-ok commented on src/main/java/com/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +            e.printStackTrace();
Мб скетчить все исключения Exception e?

2024-04-24 17:09 UTC, GUR-ok commented on src/main/java/com/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +            e.printStackTrace();
connection.rollback() кажется потерялся

2024-04-24 17:09 UTC, GUR-ok commented on src/main/java/com/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +                while (resultSet.next()) {
Лишний запрос всех товаров и проход по резалтсету. на 82 строке уже есть резалтсет и цикл по нему. новая цена тоже известна. давай там писать в файл

2024-04-24 17:09 UTC, GUR-ok commented on src/main/java/com/warehouse/scheduling/SimpleProductPriceScheduler.java
> +        System.out.println("****** Start Simple Scheduling ******");
sout

2024-04-24 17:09 UTC, GUR-ok commented on src/main/java/com/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +import java.sql.*;
схлопнутых импортов избегаем. проверить везде в изменяемых по этому мр файлах. желательно идейку настроить, чтоб не схлопывала автоматом

2024-04-24 17:09 UTC, GUR-ok commented on src/main/java/com/warehouse/service/ProductService.java
> +        Product product = productRepository.findByIdLocked(id).orElseThrow(() -> new ProductNotFoundException(id));
не имеет отношения к мр

2024-04-24 17:09 UTC, GUR-ok commented on updatedPriceProduct.txt
давай этот файл не будем класть в репу)

2024-04-24 17:11 UTC, GUR-ok commented on src/main/java/com/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +    private Connection connection;
Зачем нам конекшн в проперти синглтона? А если другой поток будет юзать шедулер? Синглтоны не должны хранить потоконебезопасного состояния. Давай конекшн объявим как локальную переменную.

2024-04-24 17:13 UTC, GUR-ok commented on src/main/java/com/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +            connection = DriverManager.getConnection(url, username, password);
А зачем мы connection пишем в проперти синглтона? А если два потока будут этот шедулер юзать? Синглотны не должны хранить потоконебезопасного состояния. Давай connection делать локальной переменной

2024-04-24 17:13 UTC, GUR-ok commented on src/main/java/com/warehouse/scheduling/OptimizedProductPriceScheduler.java
> +            connection = DriverManager.getConnection(url, username, password);
давай connection получать через datasource или entitymanagerfactory. они настроены. как минимум нужно инжектить не 3 поля, а 1 (вместо url, username, password)

2024-05-01 03:11 UTC, Margarita-Mashkova commented on src/main/java/com/warehouse/aspect/ExecutionTimeAspect.java
> +            System.out.println("Execution time for method " + className + "." + methodName + "() = " + executionTime + " ms");
Исправила все замечания

2024-05-01 09:16 UTC, GUR-ok approved these changes
можно мержить. со сквошем

2024-05-01 12:06 UTC, merged