Task3: add currency exchange rate conversion
Margarita-Mashkova/warehouse_mediasoft pull request #5
Opened 2024-05-02 01:10 UTC by Margarita-Mashkova

2024-05-04 08:13 UTC, GUR-ok requested changes

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/cache/CacheConfig.java
> +public class CacheConfig {
это в пакет java/com/warehouse/configuration

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/webclient/CurrencyServiceClientImpl.java
> +package com.warehouse.currency.webclient;
com.warehouse.currency.interaction.currencyservice
В пакете com.warehouse.currency.interaction будут потом интеграции с другими сервисами

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/CurrencyProvider.java
> +    public void setSessionCurrency(String currency) {
сеттер и геттер заменить на ломбоковоское @Data

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/CurrencyProvider.java
> +    private CurrencyServiceClient clientCurrency;
во-первых инжектить нужно через конструктор, а во вторых сюда клиента помещать не нужно. задача CurrencyProvider просто хранить установленную валюту в сессии.

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/webclient/CurrencyServiceClientImpl.java
> +    private String method;
Давай больше не будем инжектить через value.
Создай класс для пропертей для rest взаимодействия
@ConfigurationProperties

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/webclient/CurrencyServiceClientImpl.java
> +    private final WebClient webClient = WebClient.create();
WebClient нужно законфижить как бин и там в конфигах задать хост из конфигов

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/webclient/CurrencyServiceClientImpl.java
> +            log.info("Exception in method getCurrenciesFromService()", ex);
тут не инфо а error

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/webclient/CurrencyServiceClientImpl.java
> +        return null;
этот return null нужно поместить в else у if условия из 53 строки

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/webclient/CurrencyServiceClientImpl.java
> +    public CurrenciesDto getCurrenciesFromService() {
Нулл возвращать не очень хорошая практика. пометь тогда через спринговую аннотацию nullable тут возвращаемый тип

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/webclient/CurrencyServiceClientImpl.java
> +            if (response != null) {
response точно может быть null? не будет ли исключения в .bodyToMono(CurrenciesDto.class)? тогда мы в это условие никогда не зайдем

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/webclient/CurrencyServiceClientImpl.java
> +                    .uri(host + method)
тут передавать только метод. хост будет законфижен в бин вебклиента как baseurl

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/webclient/CurrencyServiceClientImpl.java
> +    public CurrenciesDto getCurrenciesFromFile() {
тут не должно быть этого метода. этот класс - клиент. он должен ходить в другой сервис

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/webclient/CurrencyServiceClientImpl.java
> +    @Cacheable(value = "currenciesDto", unless = "#result == null")
ты получается кэшируешь значение из файла. это неверно. по заданию не так

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/webclient/CurrencyServiceClientImpl.java
> +    public CurrenciesDto getCurrenciesFromFile() {
Нужно сделать обертку, которая по валюте отдает курс. Она обращается сначала к клиенту, а потом читает из файла. Работа с ресурсом файла будет там и работа с CurrencyServiceClient тоже будет там.
Называем класс ExchangeRateProvider
```
@Component
@Slf4j
@RequiredArgsConstructor
public class ExchangeRateProvider {

    private final CurrencyServiceClient currencyServiceClient ;
```
Например имеет

удобный публичный метод, который позволит передать валюту, а в ответ получит курс. не нужно будет в продукт-сервисе много логики городить. Вызвал и все.
```
public BigDecimal getExchangeRate(Currency currency) {
    return Optional.ofNullable(getExchangeRateFromService(currency))
            .orElseGet(() -> getExchangeRateFromFile(currency));
}
```
Сделай два приватных метода. получение валюты из внешнего сервиса и получение из файла
```
private @Nullable BigDecimal getExchangeRateFromService(Currency currency) {
   log.info("Получаем курс из второго сервиса или из кэша");
   return Optional.ofNullable(currencyServiceClient.getExchangeRate())
           .map(rate -> getExchangeRateByCurrency(rate, currency)).orElse(null);
}

private BigDecimal getExchangeRateFromFile(Currency currency) {
...
}

private BigDecimal getExchangeRateByCurrency(ExchangeRate exchangeRate, Currency currency) {
   return switch (currency) {
       case USD -> exchangeRate.getExchangeRateUSD();
       case CNY -> exchangeRate.getExchangeRateCNY();
       case EUR -> exchangeRate.getExchangeRateEUR();
       case RUB -> BigDecimal.ONE;
   };
}
```

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/dto/CurrenciesDto.java
> +            case ("CNY") -> CNY;
Для типов валют сделать отдельный енум. Эта логика плохая и тут быть не должна.
Когда появится енум, ты сможешь сделать метод типа
```
private BigDecimal getExchangeRateByCurrency(ExchangeRate exchangeRate, Currency currency) {
   return switch (currency) {
       case USD -> exchangeRate.getExchangeRateUSD();
       case CNY -> exchangeRate.getExchangeRateCNY();
       case EUR -> exchangeRate.getExchangeRateEUR();
       case RUB -> BigDecimal.ONE;
   };
}
```
скидывал выше

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/dto/ProductResponseDto.java
> +    private String currency;
енумом

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/service/ProductService.java
> +    @Autowired
инжектить через конструктор

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/webclient/CurrencyServiceClientImpl.java
> +@ConditionalOnProperty(name = "currency-service.web-client.enabled")
убрать тут @ConditionalOnProperty(name = "currency-service.web-client.enabled") а на моке поставить primary

2024-05-04 08:13 UTC, GUR-ok commented on src/main/java/com/warehouse/currency/webclient/CurrencyServiceClientMock.java
> +@ConditionalOnProperty(name = "currency-service.web-client.enabled", havingValue = "false")
тут добавить primary и активацию по @ConditionalOnProperty(name = "rest.currency-service.mock.enabled:false")

2024-05-04 08:13 UTC, GUR-ok commented on src/main/resources/application.yaml
> +  web-client:
```
rest:
   currency-service:
      host:
      methods: ...
      mock:
         enabled: true
```

2024-05-07 22:04 UTC, Margarita-Mashkova commented on src/main/java/com/warehouse/currency/cache/CacheConfig.java
> +public class CacheConfig {
Все замечания поправила!

2024-05-11 08:47 UTC, GUR-ok approved these changes
можно мержить со сквошем

2024-05-16 20:57 UTC, merged