Task4: add ordering products
Margarita-Mashkova/warehouse_mediasoft pull request #7
Opened 2024-05-09 07:56 UTC by Margarita-Mashkova

Диаграмма сущностей:

![warehouse_er](https://github.com/Margarita-Mashkova/warehouse_mediasoft/assets/91306848/1134dd26-b49e-4247-bec2-e4174b163b7f)

2024-05-09 08:07 UTC, Margarita-Mashkova commented
Насчет N+1 проблемы: Hibernate автоматически создает 1 запрос с JOIN для связанных сущностей (у меня это только Customer для сущности Order, т.к. не делала двунаправленные связи), поэтому получается так, что проблема не возникает

SQL запрос при вызове метода orderRepository.findById(id):

![image](https://github.com/Margarita-Mashkova/warehouse_mediasoft/assets/91306848/591d10c1-877c-48a1-ae49-7a8e54b3e429)

2024-05-11 09:14 UTC, GUR-ok requested changes
В целом очень неплохо.  Сделано очень аккуратно. Старайся при работе с несколькими таблицами следить за оптимальностью селектов. Если можно запросить одним запросом - так нужно делать (у тебя селект товаров идет по одному, и ордер запрашивается отдельно от товаров в ордере).Для оптимизации селектов попробуй использовать доп структуру - хэшмапу, тебе поможет в разработке мышление в эту сторону.

2024-05-11 09:14 UTC, GUR-ok commented on src/main/java/com/warehouse/model/Order.java
> +    private Customer customer;
У тебя n+1 не возникает, потому что тут нету связи =)    
```
    @OneToMany(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id",referencedColumnName = "id")
    private List<OrderProduct> orderedProducts;
```    
    
  Ты в сервисе поэтому сама делаешь этот лишний запрос
  170 строка сервиса 
  ``` List<OrderProductDto> existsOrderProducts = orderProductRepository.findProductsByOrderId(orderDb.getId());```
  
 Нужно запрашивать ордер вместе с заказанными товарами через квери с join-fetch 
 ```
     @Query("from OrderEntity o " +
            "left join fetch o.orderedProducts " +
            "where o.id = :orderId")
    Optional<OrderEntity> findByIdFetchOrderedProducts(UUID orderId);
```
Тогда не придется их дергать отдельно

2024-05-11 09:14 UTC, GUR-ok commented on src/main/java/com/warehouse/model/OrderProduct.java
> +    @MapsId("product_id")
@MapsId должен ссылаться на название поля класса, а не название колонки..

2024-05-11 09:14 UTC, GUR-ok commented on src/main/java/com/warehouse/repository/CustomerRepository.java
> +    boolean isLoginExists(String login);
Можно не задавать нативно квери, а использовать нейминг методов. просто назвать existsByLogin (совсем без квери). А если используешь квери если там логика посложнее, то принято через case и count так ```@Query("select case when (count(p) > 0) then true else false end from ProductEntity p where p.article = :article")```, хотя твое вроде тоже верно, просто не встречал

2024-05-11 09:14 UTC, GUR-ok commented on src/main/java/com/warehouse/service/OrderService.java
> +    private List<OrderProduct> checkOrderProductList(List<ProductInOrderDto> addedProductList, Order order) {
приватные методы всегда идут после публичных

2024-05-11 09:14 UTC, GUR-ok commented on src/main/java/com/warehouse/service/OrderService.java
> +            Product productDb = productRepository.findById(productInOrder.getId())
нужно товары искать одним запросом. У тебя для каждого товара в заказе делается селект. сделай findByIdIn, передав туда список айди. потом сделай из этого хэшмапу. сможешь за О(1) получать товара по айди.
![image](https://github.com/Margarita-Mashkova/warehouse_mediasoft/assets/76206833/6f39dc91-9659-4844-ac58-94e881f8414a)

Соответственно ProductNotFoundException бросается, если у тебя в запросе может быть 3 товара, а нашлось 2. Это нужно чекнуть.

2024-05-11 09:14 UTC, GUR-ok commented on src/main/java/com/warehouse/service/OrderService.java
> +        List<OrderProductDto> existsOrderProducts = orderProductRepository.findProductsByOrderId(orderDb.getId());
давай проекции использовать только в методе получения инфы о заказе. тут пусть подтягивается вместе с ордер, когда добавишь связь в OrderEntity. Этой строчки не будет вообще, т.к. все извлечеться вместе с ордер на 154 строке. Там проследить за N+1

2024-05-11 09:14 UTC, GUR-ok commented on src/main/java/com/warehouse/service/OrderService.java
> +        List<OrderProductDto> orderProducts = orderProductRepository.findProductsByOrderId(id);
тут аналогично методу edit

2024-05-11 09:24 UTC, GUR-ok commented on src/main/java/com/warehouse/model/Order.java
> +    @JoinColumn(name = "customer_id")
Для customer не возникает n+1?

2024-05-20 09:19 UTC, GUR-ok commented
Про кастомера понял, да. Поправь конфликты плз.

2024-05-21 10:36 UTC, Margarita-Mashkova commented on src/main/java/com/warehouse/model/Order.java
> +    @JoinColumn(name = "customer_id")
Как я поняла, когда используется стандартный метод findById(), Hibernate автоматически делает join
Потому что, например, сейчас, когда я использовала productRepository.findAllById(), появился лишний селект к категории, которая связана с продуктом

2024-05-21 11:22 UTC, Margarita-Mashkova commented on src/main/java/com/warehouse/model/Order.java
> +    @JoinColumn(name = "customer_id")
При использовании @Fetch(FetchMode.JOIN) над колонкой Category, например, у сущности Product, все равно остается дополнительные select к сущности Category при получении продукта
Поэтому я там тоже через нативный запрос сделала

2024-05-23 05:56 UTC, GUR-ok approved these changes
Ок давай мержить со сквошем! =)

2024-05-24 04:10 UTC, merged